#' Generate time-outcome fan plot
#'
#' @param psa_data A data.frame (or a list of data.frames containing) where the first column contains the model time, and subsequent columns contain the predicted output for each simulation run at the respective time. See Data format section for more information.
#'
#' @section Data format:
#'
#' The model time in the first column must contain numeric values indicating a simulation time (ex. 0, 1, 2, 3,...) or dates (ex. 01/01/2024, 01/02/2024) which must be in `R` Date format (i.e., class="Date"). If comparing simulation results across multiple scenarios, provide a list of data.frames, where each data.frame gives the output for one scenario.
#'
#' @param tmin Numeric value giving the minimum simulation time
#' @param tmax Numeric value giving the maximum simulation time
#' @param Dt Numeric vector of decision thresholds at each time between `tmin` and `tmax``
#' @param Dt_max Logical indicating whether decision threshold is a maximum (`TRUE`) or minimum (`FALSE`)
#'
#' @return ggplot or list of ggplot(s) time-outcome fan plot(s)
#' @export
plot_fan <- function(psa_data, tmin, tmax, Dt, Dt_max) {
  if (length(Dt) != length(tmin:tmax)) {
    # Return error message if Dt is not the same length as tmin:tmax
    stop(paste("Dt must be the same length as the number of time periods (tmin:tmax)."))
  } else {
    if (inherits(psa_data, "list")) {
      plot <- lapply(psa_data, plot_fan_1, tmin, tmax, Dt, Dt_max)
      plot <- stats::setNames(
        lapply(names(plot), function(name) {
          plot[[name]] + ggplot2::ggtitle(name)
        }),
        names(plot)
      )
    } else if (inherits(psa_data, "data.frame")) {
      plot <- plot_fan_1(psa_data, tmin, tmax, Dt, Dt_max)
    } else {
      stop(paste("The first argument is not a data.frame or list of data.frames"))
    }
    return(plot)
  }
}

#' Plot time-outcome fan plot for a single set of simulations
#'
#' @inheritParams plot_fan
#'
#' @return ggplot time-outcome fan plot
plot_fan_1 <- function(psa_data, tmin, tmax, Dt, Dt_max) {
  time <- one <- two <- three <- four <- five <- NULL
  l <- length(psa_data[1, ])
  percentiles_df <- psa_data[(tmin + 1):(tmax + 1), 1]
  perc_df <- c()
  for (i in (tmin + 1):(tmax + 1)) {
    q <- stats::quantile(
      as.numeric(psa_data[i, 2:l]),
      c(0.025, 0.25, 0.5, 0.75, 0.975)
    )
    perc_df <- rbind(perc_df, q)
  }
  percentiles_df <- cbind.data.frame(percentiles_df, perc_df, Dt)
  colnames(percentiles_df) <- c("time", "one", "two", "three", "four", "five", "Dt")

  plot <- ggplot2::ggplot(as.data.frame(percentiles_df), ggplot2::aes(x = time, y = three, group = 1)) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = one, ymax = five, fill = "95th %tile range"), alpha = 0.5) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = two, ymax = four, fill = "50th %tile range"), alpha = 0.4) +
    ggplot2::geom_line(ggplot2::aes(y = three, color = "Median"), linewidth = 1) +
    ggplot2::geom_line(ggplot2::aes(y = Dt, color = "Policy target"), linetype = "dashed", linewidth = 0.75) +
    ggplot2::ylab("Outcome") +
    ggplot2::xlab("Time") +
    ggplot2::theme_classic()

  plot <- plot + ggplot2::scale_color_manual(values = c(
    "Median" = "black",
    "Policy target" = "red"
  )) +
    paletteer::scale_fill_paletteer_d("calecopal::lupinus") +
    ggplot2::scale_linetype_manual(values = c(
      "Median" = "solid",
      "Policy target" = "dashed"
    ))

  plot <- plot + ggplot2::guides(fill = ggplot2::guide_legend(override.aes = list(linetype = 0)))

  plot <- plot + ggplot2::theme(
    legend.position = "bottom",
    legend.title = ggplot2::element_blank(),
    legend.text = ggplot2::element_text(size = 8)
  )

  # add caption
  time_outcomes_list <- calculate_time(psa_data, tmin, tmax, Dt, Dt_max)
  time_output_captions <- caption_time(time_outcomes_list, Dt_max)

  plot <- plot + ggplot2::labs(subtitle = time_output_captions) +
    ggplot2::theme(plot.subtitle = ggtext::element_textbox_simple(size = 9))

  plot <- gen_stand_descr(plot)

  return(plot)
}

#' Generate time caption for time-outcome fan plot
#'
#' @param time_outcomes Dataframe or list of dataframe(s) generated by calculate_time()
#' @param Dt_max Logical indicating whether decision threshold is a maximum (`TRUE`) or minimum (`FALSE`)
#'
#' @return A character vector or list of character vector(s) of the time caption
caption_time <- function(time_outcomes, Dt_max) {
  if (inherits(time_outcomes, "list")) {
    stats <- lapply(time_outcomes, caption_time_1, Dt_max)
  } else {
    stats <- caption_time_1(time_outcomes, Dt_max)
  }
  return(stats)
}

#' Generate time caption for time-outcome fan plot for a single set of simulations
#'
#' @inheritParams caption_time
#'
#' @return A character vector of the time caption
caption_time_1 <- function(time_outcomes, Dt_max) {
  paste(
    "The threshold is", ifelse(Dt_max == TRUE, "exceeded", "not reached"),
    "in", scales::percent(time_outcomes[1, 1], accuracy = 1),
    "of all simulations. The first", ifelse(Dt_max == TRUE, "exceedance", "short fall"),
    "occurs at median simulation time", round(time_outcomes[1, 2], digits = 0), "(95% CI",
    round(time_outcomes[1, 3], digits = 0),
    "-", round(time_outcomes[1, 4], digits = 0), ") and lasts for a median of ",
    round(time_outcomes[1, 5], digits = 0), "(95% CI",
    round(time_outcomes[1, 6], digits = 0), "-",
    round(time_outcomes[1, 7], digits = 0), ") simulation time steps on average.<br>"
  )
}
